services:
  server:
    build: C:\Users\joaov\OneDrive\Desktop\IoT-Industrial\server
    ports:
      - "5000:5000"

  gateway:
    build: C:\Users\joaov\OneDrive\Desktop\IoT-Industrial\sensores
    command: python gateway.py
    depends_on:
      - server

  sensor:
    build: C:\Users\joaov\OneDrive\Desktop\IoT-Industrial\sensores
    command: python sensor.py
    depends_on:
      - gateway

  atuador:
    build: C:\Users\joaov\OneDrive\Desktop\IoT-Industrial\sensores
    command: python atuador.py
    ports:
      - "6000:6000"
    depends_on:
      - server

  cliente:
    build: C:\Users\joaov\OneDrive\Desktop\IoT-Industrial\interface
    depends_on:
      - server
      - atuador