services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5050:5000"
    environment:
      - ALARME_IP=${EDGE_HOST_IP}
      - RESFRIAMENTO_IP=${EDGE_HOST_IP}
    volumes:
      - ./data:/app/data

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - HTTP_URL=http://server:5000
      - UDP_PORT=5001
    ports:
      - "5001:5001/udp"
    depends_on:
      - server