services:
  alarme:
    build: ../services/atuadores
    container_name: alarme
    command: python -u alarme.py
    ports:
      - "6000:6000"
    volumes:
      - ./data:/app/data

  resfriamento:
    build: ../services/atuadores
    container_name: resfriamento
    command: python -u resfriamento.py
    ports:
      - "6001:6001"
    volumes:
      - ./data:/app/data
    environment:
      - SENSORES_TEMP=sensor_temp_1,sensor_temp_2,sensor_temp_3
      - TCP_SENSOR_PORT=7000

  sensor_temp_1:
    build: ../services/sensores
    container_name: sensor_temp_1
    command: python -u temperatura.py
    environment:
      - SENSOR_ID=sensor_temp_1
      - SERVER_IP=${CORE_HOST_IP}
      - UDP_PORT=5001
      - TCP_PORT=7000

  sensor_temp_2:
    build: ../services/sensores
    container_name: sensor_temp_2
    command: python -u temperatura.py
    environment:
      - SENSOR_ID=sensor_temp_2
      - SERVER_IP=${CORE_HOST_IP}
      - UDP_PORT=5001
      - TCP_PORT=7000

  sensor_temp_3:
    build: ../services/sensores
    container_name: sensor_temp_3
    command: python -u temperatura.py
    environment:
      - SENSOR_ID=sensor_temp_3
      - SERVER_IP=${CORE_HOST_IP}
      - UDP_PORT=5001
      - TCP_PORT=7000

  sensor_umidade_1:
    build: ../services/sensores
    container_name: sensor_umidade_1
    command: python -u umidade.py
    environment:
      - SENSOR_ID=sensor_umidade_1
      - SERVER_IP=${CORE_HOST_IP}
      - UDP_PORT=5001

  sensor_umidade_2:
    build: ../services/sensores
    container_name: sensor_umidade_2
    command: python -u umidade.py
    environment:
      - SENSOR_ID=sensor_umidade_2
      - SERVER_IP=${CORE_HOST_IP}
      - UDP_PORT=5001